# fly.toml docs and default values at https://fly.io/docs/reference/configuration/

app = "willnorris-auth"
primary_region = "lax"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 9091
  force_https = true

[[metrics]]
  port = 9959
  path = "/metrics"
  https = false
