app = "willnorris-auth"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[[mounts]]
source = "data"
destination = "/data"

[http_service]
internal_port = 9091
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1

[[metrics]]
port = 9959
path = "/metrics"
https = false
