# fly.toml docs and default values at https://fly.io/docs/reference/configuration/

app = "willnorris-auth"
primary_region = "lax"

[[mounts]]
  source = "data"
  destination = "/app/data"

[http_service]
  internal_port = 1411
  force_https = true

# [[metrics]]
#   port = 9464
#   path = "/metrics"
#   https = false
